# Generated by Django 3.0.6 on 2020-05-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0002_auto_20200523_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='responder',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='sessions.Session', verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='post',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_responded_to', to='sessions.Session', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='sessions.Session', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sessions.Session', verbose_name='post'),
        ),
    ]
