# Generated by Django 3.0.6 on 2020-06-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0003_auto_20200524_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_responded_to', to='sessions.Session', verbose_name='responder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sessions.Session', verbose_name='user'),
        ),
    ]
